version: '3.1'

services:

  cassandra00:
    build: ./cassandra
    ports: 
      - '7000:7000'
      - '7001:7001'
      - '7199:7199'
      -  9042:9042
      -  9160:9160
      - '9404:9404'
    environment:
        CASSANDRA_KEYSPACE: "go_do"
        CASSANDRA_LISTEN_ADDRESS: "127.0.0.50"

  api:
      build: ./api
      ports:
        - 8080:8080
      environment:
          MICRO_ADDRESS: ":8080"
          MICRO_REGISTRY: "mdns"
          MICRO_API_HANDLER: "rpc"
          MICRO_NAMESPACE: "go_do"
          CORS_ALLOWED_METHODS: "POST"
          CORS_ALLOWED_ORIGINS: "http://localhost:3000" 

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_KEYSPACE: "go_do"
      DB_HOST: "cassandra00"
      DB_PORT: "9042"
    depends_on:
      - cassandra00
      