FROM golang:1.12.1-alpine as build_base
RUN apk add bash ca-certificates git gcc g++ libc-dev

WORKDIR /app/task-service

ENV GO111MODULE=on

COPY go.mod .
COPY go.sum .

RUN go mod download

FROM build_base AS builder

COPY ./task-service .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo  -o task-service

FROM alpine:latest

RUN apk --no-cache add ca-certificates

RUN mkdir /app
WORKDIR /app
COPY --from=builder /app/task-service .

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.0/wait /wait
RUN chmod +x /wait

## Launch the wait tool and then your application
CMD /wait && ./task-service

